- hosts: servers
  become: yes
  tasks:
    - name: Install dnsmasq
      apt: name=dnsmasq

    - name: Enable dnsmasq
      service: name=dnsmasq enabled=yes

    - name: Copy dnsmasq configuration
      copy: src=dnsmasq.conf dest=/etc/dnsmasq.conf
      notify: Restart dnsmasq

    - name: Copy example.com configuration
      copy: src=example.com dest=/etc/dnsmasq.d/
      notify: Restart dnsmasq

    - name: Copy hosts file
      copy: src=hosts dest=/etc/hosts
      notify: Restart dnsmasq

  handlers:
    - name: Restart dnsmasq
      service: name=dnsmasq state=restarted

- hosts: clients
  become: yes
  tasks:
    - name: Copy resolvconf configuration
      copy: src=head dest=/etc/resolvconf/resolv.conf.d/
      notify: 
        - Enable resolvconf updates
        - Update resolvconf

  handlers:
    - name: Enable resolvconf updates
      command: resolvconf --enable-updates

    - name: Update resolvconf
      command: resolvconf -u

- hosts: app
  become: yes
  tasks:
    - name: Create a group for application
      group: name=app

    - name: Create a user for application
      user:
        name: app
        comment: Service account for application
        uid: 1001
        group: app
        create_home: yes

    - name: Copy application
      # the leading 0 is because 755 is an octal number
      copy: src=app dest=/home/app/app mode=0755
      notify: Restart application

    - name: Copy unit file
      copy: src=app.service dest=/etc/systemd/system/
      notify: Restart application

  handlers:
    - name: Restart application
      systemd:
        name: app.service
        state: restarted
        daemon_reload: yes
