#!/usr/bin/env bash
# A basic web application
# https://www.digitalocean.com/community/tutorials/how-to-use-netcat-to-establish-and-test-tcp-and-udp-connections-on-a-vps
while true; do
	printf 'HTTP/1.1 200 OK\n\n%s\n' '<h1>Hello world</h1>' | netcat -l 3000
done
